# Generated by Django 3.0.7 on 2020-07-08 13:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/users/no_photo.png', upload_to=account.models.user_directory_path),
        ),
    ]
